version: '3'
services:
    cache:
        image: memcached:latest
        ports:
            - 11211:11211
    flask:
        build: .
        ports:
            - 8080:8080
        environment:
            - MEMCACHED_HOST=cache
        links:
            - "cache:cache"

