version: '3'
services:
    cache:
        image: memcached:latest
        ports:
            - 11211:11211
        networks: 
            - my-network
    flask:
        build: .
        ports:
            - 8080:8080
        environment:
            - MEMCACHED_HOST=cache
        networks:
            my-network:
                aliases:
                    - flask-app
        depends_on:
            - cache
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        restart: always
        depends_on:
            - flask
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - my-network
    
networks: 
    my-network:
